### ISSUE TITLE
italic font support

### ISSUE THREAD

**Issue by ipatch** [philtr/dotfiles#4]
Not sure if _italic_ font is your thing, but you might want to check out [this](https://medium.com/@dubistkomisch/how-to-actually-get-italics-and-true-colour-to-work-in-iterm-tmux-vim-9ebe55ebc2be) article, it helped me with getting italic font working with my shell, tmux, and Vim.

![italic](https://i.imgur.com/9WF5n5Y.png)

cheers 🍻
Chris

**Comment by philtr** [comment]
I had it working at one point—it's honestly too much work to make it worth it IMO. Thanks though!
